server:
  port: $port
  servlet.contextPath: /v0.1

# LOGGING Properties
logging:
  path: './logs_${HOSTNAME}/'
  level:
    root: INFO
    org:
      springframework:
        web: INFO
        boot: INFO
      apache.solr: INFO
      hibernate:
        SQL: INFO
        type.descriptor.sql.BasicBinder: INFO

# To avoid errors while parsing null values in objects
spring.jackson.default-property-inclusion: NON_NULL

# Configuration for MongoDB
mongodb:
  project:
    database: $mongodb_db
    app:
      user: $NOT_USED
      password: $NOT_USED
      authenticationDatabase: $NOT_USED
      machine.port: $NOT_USED
  projects:
    replicate:
      hosts: $NOT_USED
      ports: $NOT_USED
    single.machine.host: $NOT_USED
    machine.uri: $mongodb_machine_uri
  molecules:
    database: $mongodb_molecules_db
    machine.uri: $mongodb_molecules_machine_uri

mongo.single.machine: $NOT_USED

##### Solr CLoud #####
solr:
  master:
    hh.url: $solr_master_hh_url
    hx.url: $solr_master_hx_url
spring.data.solr.zk-host:
  hh: $solr_zk_hh
  hx: $solr_zk_hx
spring.pridedb.solr:
  hh.url: $solr_pridedb_hh_url
  hx.url: $solr_pridedb_hx_url
